import { Course } from "../course-interface";

export const courses: Course[] = [
  {
    title: "Área da Saúde",
    description: [
      "Técnico em Agente Comunitário de Saúde",
      "Técnico em Análises Clínicas",
      "Técnico em Cuidados de Idosos",
      "Técnico em Enfermagem",
      "Técnico em Equipamentos Biomédicos",
      "Técnico em Estética",
      "Técnico em Farmácia",
      "Técnico em Gerência em Saúde",
      "Técnico em Nutrição e Dietética",
      "Técnico em Radiologia",
      "Técnico em Saúde Bucal",
      "Técnico em Veterinária",
    ],
  },
  {
    title: "Administração e Gestão",
    description: [
      "Técnico em Administração",
      "Técnico em Contabilidade",
      "Técnico em Logística",
      "Técnico em Marketing",
      "Técnico em Qualidade",
      "Técnico em Recursos Humanos",
      "Técnico em Secretariado Escolar",
      "Técnico em Segurança do Trabalho",
      "Técnico em Serviços Jurídicos",
      "Técnico em Transações Imobiliárias",
      "Técnico em Vendas",
      "Curso Técnico em Eventos",
    ],
  },
  {
    title: "Engenharia e Manutenção",
    description: [
      "Técnico em Automação Industrial",
      "Técnico em Eletromecânica",
      "Técnico em Eletrotécnica",
      "Técnico em Eletrônica",
      "Técnico em Manutenção de Máquinas Industriais",
      "Técnico em Metalurgia",
      "Técnico em Refrigeração e Climatização",
      "Técnico em Soldagem",
      "Técnico em Manutenção de Máquinas Navais",
    ],
  },
  {
    title: "Construção e Infraestrutura",
    description: [
      "Técnico em Agrimensura",
      "Técnico em Edificações",
      "Técnico em Mineração",
      "Técnico em Segurança do Trabalho",
      "Técnico em Prevenção e Combate ao Incêndio",
      "Curso Técnico em Defesa Civil",
      "Curso Técnico em Trânsito",
    ],
  },
  {
    title: "Tecnologia e Informática",
    description: [
      "Técnico em Biotecnologia",
      "Técnico em Design Gráfico",
      "Técnico em Desenvolvimento de Sistemas",
      "Técnico em Informática para Internet",
      "Técnico em Redes de Computadores",
      "Técnico em Sistemas de Energia Renovável",
      "Técnico em Telecomunicações",
      "Técnico em Tradução e Interpretação de Libras",
    ],
  },
  {
    title: "Meio Ambiente e Agropecuária",
    description: [
      "Técnico em Agricultura",
      "Técnico em Agropecuária",
      "Técnico em Agroindústria",
      "Técnico em Aquicultura",
      "Técnico em Meio Ambiente",
    ],
  },
  {
    title: "Área de Serviços",
    description: [
      "Técnico em Gastronomia",
      "Técnico em Óptica",
      "Técnico em Design de Interiores",
      "Técnico em Guia de Turismo",
    ],
  },
];
