import { Course } from "../course-interface";

export const courses: Course[] = [
  {
    title: "Área da Saúde",
    description: [
      "Técnico em Agente Comunitário de Saúde",
      "Técnico em Análises Clínicas",
      "Técnico em Cuidados de Idosos",
      "Técnico em Enfermagem",
      "Técnico em Equipamentos Biomédicos",
      "Técnico em Estética",
      "Técnico em Farmácia",
      "Técnico em Gerência em Saúde",
      "Técnico em Nutrição e Dietética",
      "Técnico em Radiologia",
      "Técnico em Saúde Bucal",
      "Técnico em Veterinária",
    ],
  },
  {
    title: "Administração e Gestão",
    description: [
      "Técnico em Administração",
      "Técnico em Contabilidade",
      "Técnico em Logística",
      "Técnico em Marketing",
      "Técnico em Qualidade",
      "Técnico em Recursos Humanos",
      "Técnico em Secretariado Escolar",
      "Técnico em Segurança do Trabalho",
      "Técnico em Serviços Jurídicos",
      "Técnico em Transações Imobiliárias",
      "Técnico em Vendas",
      "Curso Técnico em Eventos",
    ],
  },
  {
    title: "Engenharia e Manutenção",
    description: [
      "Técnico em Automação Industrial",
      "Técnico em Eletrônica",
      "Técnico em Eletrotécnica",
      "Técnico em Mecatrônica",
      "Técnico em Manutenção de Máquinas",
      "Técnico em Soldagem",
      "Técnico em Metalurgia",
      "Técnico em Refrigeração e Climatização",
      "Técnico em Segurança do Trabalho",
      "Técnico em Manutenção de Máquinas Navais",
    ],
  },
  {
    title: "Construção e Infraestrutura",
    description: [
      "Técnico em Agrimensura",
      "Técnico em Edificações",
      "Técnico em Mineração",
      "Técnico em Segurança do Trabalho",
      "Técnico em Saneamento",
      "Técnico em Estradas",
      "Curso Técnico em Defesa Civil",
      "Curso Técnico em Topografia",
    ],
  },
  {
    title: "Tecnologia e Informática",
    description: [
      "Técnico em Informática",
      "Técnico em Desenvolvimento de Sistemas",
      "Técnico em Programação de Jogos Digitais",
      "Técnico em Redes de Computadores",
      "Técnico em Segurança da Informação",
      "Técnico em Sistemas de Energia Renovável",
      "Técnico em Banco de Dados",
      "Técnico em Tradução e Interpretação de Libras",
    ],
  },
  {
    title: "Meio Ambiente e Agropecuária",
    description: [
      "Técnico em Meio Ambiente",
      "Técnico em Agropecuária",
      "Técnico em Agricultura",
      "Técnico em Zootecnia",
      "Técnico em Piscicultura",
      "Técnico em Gestão Ambiental",
      "Técnico em Recursos Hídricos",
      "Técnico em Saúde Ambiental",
    ],
  },
  {
    title: "Área de Serviços",
    description: [
      "Técnico em Gastronomia",
      "Técnico em Óptica",
      "Técnico em Design de Interiores",
      "Técnico em Guia de Turismo",
    ],
  },
];
